
version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbcontainerdata:/data/db
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Abc123*
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  mongodbcontainerdata:
  pgdata: